apiVersion: batch/v1
kind: Job
metadata:
  name: commit-and-push
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: run
        image: golang
        command:
          - /bin/bash
          - -cex
          - |
            cd `mktemp -d`

            git clone http://git-serve/foo.git .

            git config user.email "hello@example.com"
            git config user.name "hello"

            echo "foo" > ./foo
            git add --all .&& git commit -m "foo" && git push origin HEAD
