---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: git-serve
imagePullSecrets:
  - name: registry-credentials


---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K


---
apiVersion: v1
kind: Service
metadata:
  name: git-serve
  labels:
     app.kubernetes.io/name: git-serve
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
     app.kubernetes.io/name: git-serve


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-serve
spec:
  selector:
    matchLabels:
       app.kubernetes.io/name: git-serve
  replicas: 1
  template:
    metadata:
      labels:
         app.kubernetes.io/name: git-serve
    spec:
      automountServiceAccountToken: false
      serviceAccount: git-serve
      volumes:
        - name: git-repositories
          emptyDir: {}
      imagePullSecrets:
        - name: registry-credentials
      containers:
        - name: git-serve
          image: cirocosta/git-serve
          args:
            - git-serve
            - -addr=:8080                   # address to bind the server to
            - -directory=/git-repositories  # where git repositories should be stored
            - -git=/usr/bin/git             # absolute path to git executable
            - -verbose                      # turn verbose logs on/off
          volumeMounts:
            - mountPath: /git-repositories
              name: git-repositories
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - all
          resources:
            requests:
              cpu: 200m
              memory: 100Mi
