---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config
sources:
  - image: image
    path: .
destinations:
  - image: image
    newImage: docker.io/cirocosta/git-serve


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: git-serve
imagePullSecrets:
  - name: registry-credentials


---
apiVersion: v1
kind: Secret
metadata:
  name: registry-credentials
  annotations:
    secretgen.carvel.dev/image-pull-secret: ""
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: e30K


---
apiVersion: v1
kind: Service
metadata:
  name: git-serve
  labels:
     app.kubernetes.io/name: git-serve
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: ssh
      port: 22
      targetPort: 2222
      protocol: TCP
  selector:
     app.kubernetes.io/name: git-serve


---
apiVersion: secretgen.k14s.io/v1alpha1
kind: Password
metadata:
  name: git-serve-http-creds
spec:
  length: 24
  secretTemplate:
    type: kubernetes.io/basic-auth
    stringData:
      username: admin
      password: $(value)


---
apiVersion: secretgen.k14s.io/v1alpha1
kind: SSHKey
metadata:
  name: git-serve-ssh-server-keys
spec: {}


---
apiVersion: secretgen.k14s.io/v1alpha1
kind: SSHKey
metadata:
  name: git-serve-ssh-client-keys
spec: {}


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: git-serve
spec:
  selector:
    matchLabels:
       app.kubernetes.io/name: git-serve
  replicas: 1
  template:
    metadata:
      labels:
         app.kubernetes.io/name: git-serve
    spec:
      automountServiceAccountToken: false
      serviceAccount: git-serve
      volumes:
        - name: git-repositories
          emptyDir: {}
        - name: ssh-server-keys
          secret:
            secretName: git-serve-ssh-server-keys
            items:
              - key: ssh-privatekey
                path: ssh-privatekey
        - name: ssh-client-keys
          secret:
            secretName: git-serve-ssh-server-keys
            items:
              - key: ssh-authorizedkey
                path: ssh-authorizedkey
      imagePullSecrets:
        - name: registry-credentials
      containers:
        - name: git-serve
          image: image
          env:
            - name: GIT_SERVE_HTTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: git-serve-http-creds
                  key: username
            - name: GIT_SERVE_HTTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: git-serve-http-creds
                  key: password
          args:
            - git-serve
            - -v
            - -data-dir=/git-repositories
            - -ssh-authorized-keys=/ssh-client-keys/ssh-authorizedkey
            - -ssh-host-key=/ssh-server-keys/ssh-privatekey
          volumeMounts:
            - mountPath: /git-repositories
              name: git-repositories
            - mountPath: /ssh-server-keys
              name: ssh-server-keys
              readOnly: true
            - mountPath: /ssh-client-keys
              name: ssh-client-keys
              readOnly: true
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - all
          resources:
            requests:
              cpu: 200m
              memory: 100Mi
