---
apiVersion: kbld.k14s.io/v1alpha1
kind: Config
searchRules:
  - valueMatcher:
      imageRepo: cirocosta/git-serve
sources:
  - image: cirocosta/git-serve
    path: .
destinations:
  - image: cirocosta/git-serve
    newImage: docker.io/cirocosta/git-serve

---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller
  name: system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: system
  labels:
    control-plane: controller
spec:
  selector:
    matchLabels:
      control-plane: controller
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - image: cirocosta/git-serve
        name: controller
        env:
          - name: GIT_SERVE_DEFAULT_IMAGE
            value: cirocosta/git-serve
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 500m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 20Mi
        volumeMounts:
        - mountPath: /artifacts
          name: artifact-cache
      serviceAccountName: controller
      terminationGracePeriodSeconds: 10
